/* emit.c - phase-1 skeleton emission. See emit.h. */
#include "emit.h"
#include <stdio.h>
#include <string.h>

static int write_file(const char *path, const char *contents) {
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    fputs(contents, f);
    fclose(f);
    return 0;
}

int emit_skeleton(const char *outdir, const lnx_info_t *info,
                  const char *rom_label) {
    char path[1024];
    char buf[4096];

    (void)info;

    snprintf(path, sizeof(path), "%s/recomp_funcs.h", outdir);
    snprintf(buf, sizeof(buf),
        "/* recomp_funcs.h - generated by m65c02recomp (phase-1 skeleton).\n"
        " * Source ROM: %s\n"
        " *\n"
        " * Phase 2 replaces this with one prototype per discovered 65SC02\n"
        " * routine (lynx_func_<addr>), against the lynxrecomp runtime. */\n"
        "#ifndef RECOMP_FUNCS_H\n"
        "#define RECOMP_FUNCS_H\n"
        "#include \"lynxrecomp/cpu.h\"\n"
        "/* TODO(phase 2): generated prototypes. */\n"
        "#endif\n",
        rom_label ? rom_label : "(unknown)");
    if (write_file(path, buf) != 0) return -1;

    snprintf(path, sizeof(path), "%s/recomp_funcs.c", outdir);
    snprintf(buf, sizeof(buf),
        "/* recomp_funcs.c - generated by m65c02recomp (phase-1 skeleton).\n"
        " * Source ROM: %s\n"
        " *\n"
        " * Nothing is translated yet: function discovery (analyze.c) and a\n"
        " * decrypted code image (docs/BOOT.md) are phase-2 prerequisites.\n"
        " * This file exists so the per-game CMake target links today. */\n"
        "#include \"recomp_funcs.h\"\n"
        "/* TODO(phase 2): one lynx_func_<addr> per routine, each line\n"
        " * annotated with its address + original disassembly. */\n",
        rom_label ? rom_label : "(unknown)");
    if (write_file(path, buf) != 0) return -1;

    return 0;
}
