/* emit.c - C emission for the recompiler. See emit.h.
 *
 * emit_functions() is the real translator: one readable C function per
 * discovered routine, each instruction annotated with its address + disassembly
 * and lowered to a lynxrecomp runtime helper call (recomp_rt.h). Intra-function
 * control flow becomes labels + goto; JSR becomes a C call; RTS/RTI become
 * return; control that leaves the image becomes a runtime hook. */
#include "emit.h"
#include "decode.h"
#include <stdio.h>
#include <string.h>

static int write_file(const char *path, const char *contents) {
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    fputs(contents, f);
    fclose(f);
    return 0;
}

int emit_skeleton(const char *outdir, const lnx_info_t *info,
                  const char *rom_label) {
    char path[1024];
    char buf[4096];
    (void)info;

    snprintf(path, sizeof(path), "%s/recomp_funcs.h", outdir);
    snprintf(buf, sizeof(buf),
        "/* recomp_funcs.h - generated by m65c02recomp (skeleton).\n"
        " * Source ROM: %s */\n"
        "#ifndef RECOMP_FUNCS_H\n#define RECOMP_FUNCS_H\n"
        "#include \"lynxrecomp/recomp_rt.h\"\n#endif\n",
        rom_label ? rom_label : "(unknown)");
    if (write_file(path, buf) != 0) return -1;

    snprintf(path, sizeof(path), "%s/recomp_funcs.c", outdir);
    snprintf(buf, sizeof(buf),
        "/* recomp_funcs.c - generated by m65c02recomp (skeleton).\n"
        " * Source ROM: %s\n * No functions discovered yet. */\n"
        "#include \"recomp_funcs.h\"\n",
        rom_label ? rom_label : "(unknown)");
    return write_file(path, buf);
}

/* ---- real emitter ---- */

/* Is `a` reachable as a goto target inside this function (start, or a recorded
 * branch/jump target)? Used to resolve goto vs. call. */
static int is_label(const func_t *f, uint16_t a) {
    if (a == f->start) return 1;
    for (int i = 0; i < f->nlabels; i++) if (f->labels[i] == a) return 1;
    return 0;
}
/* Is `a` an actual branch/jump target (so a C label must be emitted there)?
 * Excludes the implicit start unless something branches back to it. */
static int is_branch_target(const func_t *f, uint16_t a) {
    for (int i = 0; i < f->nlabels; i++) if (f->labels[i] == a) return 1;
    return 0;
}
static int is_func(const func_table_t *t, uint16_t a) {
    return func_table_find(t, a) != NULL;
}
static int in_image(const func_table_t *t, const uint8_t *rom, size_t sz,
                    uint16_t base, uint16_t a) {
    (void)t; (void)rom;
    return a >= base && (size_t)(a - base) < sz;
}

/* Effective-address C expression for the addressing modes that touch memory. */
static void addr_expr(const insn_t *in, char *out, int n) {
    switch (in->mode) {
        case AM_ZP:  snprintf(out, n, "0x%02X", in->operand); break;
        case AM_ZPX: snprintf(out, n, "(uint8_t)(0x%02X + lynx_cpu.x)", in->operand); break;
        case AM_ZPY: snprintf(out, n, "(uint8_t)(0x%02X + lynx_cpu.y)", in->operand); break;
        case AM_ABS: snprintf(out, n, "0x%04X", in->operand); break;
        case AM_ABX: snprintf(out, n, "(uint16_t)(0x%04X + lynx_cpu.x)", in->operand); break;
        case AM_ABY: snprintf(out, n, "(uint16_t)(0x%04X + lynx_cpu.y)", in->operand); break;
        case AM_IZX: snprintf(out, n, "lynx_zp_ptr((uint8_t)(0x%02X + lynx_cpu.x))", in->operand); break;
        case AM_IZY: snprintf(out, n, "(uint16_t)(lynx_zp_ptr(0x%02X) + lynx_cpu.y)", in->operand); break;
        case AM_IZP: snprintf(out, n, "lynx_zp_ptr(0x%02X)", in->operand); break;
        default:     snprintf(out, n, "0 /*?*/"); break;
    }
}
/* Read-value C expression (immediate literal, or a memory read). */
static void rd_expr(const insn_t *in, char *out, int n) {
    if (in->mode == AM_IMM) { snprintf(out, n, "0x%02X", in->operand); return; }
    char a[64]; addr_expr(in, a, sizeof(a));
    snprintf(out, n, "lynx_mem_read(%s)", a);
}

static const char *branch_cond(const char *m) {
    if (!strcmp(m,"BPL")) return "!lynx_cpu.n";
    if (!strcmp(m,"BMI")) return "lynx_cpu.n";
    if (!strcmp(m,"BVC")) return "!lynx_cpu.v";
    if (!strcmp(m,"BVS")) return "lynx_cpu.v";
    if (!strcmp(m,"BCC")) return "!lynx_cpu.c";
    if (!strcmp(m,"BCS")) return "lynx_cpu.c";
    if (!strcmp(m,"BNE")) return "!lynx_cpu.z";
    if (!strcmp(m,"BEQ")) return "lynx_cpu.z";
    return NULL;
}

/* Emit the C body for one instruction (no leading comment). */
static void emit_insn(FILE *f, const insn_t *in, const func_t *fn,
                      const func_table_t *t, const uint8_t *rom, size_t sz,
                      uint16_t base) {
    const char *m = in->mnemonic;
    char a[80], v[96];

    /* simple register / flag ops first */
    if (!strcmp(m,"NOP")) { fprintf(f, "; /* nop */"); return; }
    if (!strcmp(m,"CLC")) { fprintf(f, "lynx_cpu.c = 0;"); return; }
    if (!strcmp(m,"SEC")) { fprintf(f, "lynx_cpu.c = 1;"); return; }
    if (!strcmp(m,"CLI")) { fprintf(f, "lynx_cpu.i = 0;"); return; }
    if (!strcmp(m,"SEI")) { fprintf(f, "lynx_cpu.i = 1;"); return; }
    if (!strcmp(m,"CLD")) { fprintf(f, "lynx_cpu.d = 0;"); return; }
    if (!strcmp(m,"SED")) { fprintf(f, "lynx_cpu.d = 1;"); return; }
    if (!strcmp(m,"CLV")) { fprintf(f, "lynx_cpu.v = 0;"); return; }
    if (!strcmp(m,"INX")) { fprintf(f, "lynx_inx();"); return; }
    if (!strcmp(m,"INY")) { fprintf(f, "lynx_iny();"); return; }
    if (!strcmp(m,"DEX")) { fprintf(f, "lynx_dex();"); return; }
    if (!strcmp(m,"DEY")) { fprintf(f, "lynx_dey();"); return; }
    if (!strcmp(m,"TAX")) { fprintf(f, "lynx_tax();"); return; }
    if (!strcmp(m,"TAY")) { fprintf(f, "lynx_tay();"); return; }
    if (!strcmp(m,"TXA")) { fprintf(f, "lynx_txa();"); return; }
    if (!strcmp(m,"TYA")) { fprintf(f, "lynx_tya();"); return; }
    if (!strcmp(m,"TSX")) { fprintf(f, "lynx_tsx();"); return; }
    if (!strcmp(m,"TXS")) { fprintf(f, "lynx_txs();"); return; }
    if (!strcmp(m,"PHA")) { fprintf(f, "lynx_pha();"); return; }
    if (!strcmp(m,"PHX")) { fprintf(f, "lynx_phx();"); return; }
    if (!strcmp(m,"PHY")) { fprintf(f, "lynx_phy();"); return; }
    if (!strcmp(m,"PHP")) { fprintf(f, "lynx_php();"); return; }
    if (!strcmp(m,"PLA")) { fprintf(f, "lynx_pla();"); return; }
    if (!strcmp(m,"PLX")) { fprintf(f, "lynx_plx();"); return; }
    if (!strcmp(m,"PLY")) { fprintf(f, "lynx_ply();"); return; }
    if (!strcmp(m,"PLP")) { fprintf(f, "lynx_plp();"); return; }

    /* loads / stores / logical / arithmetic on a value */
    if (!strcmp(m,"LDA")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_lda(%s);", v); return; }
    if (!strcmp(m,"LDX")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_ldx(%s);", v); return; }
    if (!strcmp(m,"LDY")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_ldy(%s);", v); return; }
    if (!strcmp(m,"ORA")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_ora(%s);", v); return; }
    if (!strcmp(m,"AND")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_and(%s);", v); return; }
    if (!strcmp(m,"EOR")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_eor(%s);", v); return; }
    if (!strcmp(m,"ADC")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_adc(%s);", v); return; }
    if (!strcmp(m,"SBC")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_sbc(%s);", v); return; }
    if (!strcmp(m,"CMP")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_cmp(%s);", v); return; }
    if (!strcmp(m,"CPX")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_cpx(%s);", v); return; }
    if (!strcmp(m,"CPY")) { rd_expr(in,v,sizeof(v)); fprintf(f, "lynx_cpy(%s);", v); return; }
    if (!strcmp(m,"BIT")) {
        rd_expr(in,v,sizeof(v));
        fprintf(f, in->mode == AM_IMM ? "lynx_bit_imm(%s);" : "lynx_bit(%s);", v);
        return;
    }
    if (!strcmp(m,"STA")) { addr_expr(in,a,sizeof(a)); fprintf(f, "lynx_mem_write(%s, lynx_cpu.a);", a); return; }
    if (!strcmp(m,"STX")) { addr_expr(in,a,sizeof(a)); fprintf(f, "lynx_mem_write(%s, lynx_cpu.x);", a); return; }
    if (!strcmp(m,"STY")) { addr_expr(in,a,sizeof(a)); fprintf(f, "lynx_mem_write(%s, lynx_cpu.y);", a); return; }
    if (!strcmp(m,"STZ")) { addr_expr(in,a,sizeof(a)); fprintf(f, "lynx_mem_write(%s, 0);", a); return; }

    /* read-modify-write / shifts (A or memory) */
    if (!strcmp(m,"INC") || !strcmp(m,"DEC") || !strcmp(m,"ASL") ||
        !strcmp(m,"LSR") || !strcmp(m,"ROL") || !strcmp(m,"ROR") ||
        !strcmp(m,"TSB") || !strcmp(m,"TRB")) {
        const char *op =
            !strcmp(m,"INC") ? "lynx_alu_inc" : !strcmp(m,"DEC") ? "lynx_alu_dec" :
            !strcmp(m,"ASL") ? "lynx_alu_asl" : !strcmp(m,"LSR") ? "lynx_alu_lsr" :
            !strcmp(m,"ROL") ? "lynx_alu_rol" : !strcmp(m,"ROR") ? "lynx_alu_ror" :
            !strcmp(m,"TSB") ? "lynx_alu_tsb" : "lynx_alu_trb";
        if (in->mode == AM_ACC) {
            if (!strcmp(m,"INC")) fprintf(f, "lynx_inc_a();");
            else if (!strcmp(m,"DEC")) fprintf(f, "lynx_dec_a();");
            else fprintf(f, "lynx_cpu.a = %s(lynx_cpu.a);", op);
        } else {
            addr_expr(in,a,sizeof(a));
            fprintf(f, "{ uint16_t _ea = %s; lynx_mem_write(_ea, %s(lynx_mem_read(_ea))); }", a, op);
        }
        return;
    }

    /* Rockwell bit ops on zero page */
    if (!strncmp(m,"RMB",3)) { fprintf(f, "{ uint8_t _z = 0x%02X; lynx_mem_write(_z, lynx_mem_read(_z) & (uint8_t)~(1u<<%d)); }", in->operand, in->bit); return; }
    if (!strncmp(m,"SMB",3)) { fprintf(f, "{ uint8_t _z = 0x%02X; lynx_mem_write(_z, lynx_mem_read(_z) | (uint8_t)(1u<<%d)); }", in->operand, in->bit); return; }
    if (!strncmp(m,"BBR",3)) { fprintf(f, "if ((lynx_mem_read(0x%02X) & (1u<<%d)) == 0) goto L_%04X;", in->operand, in->bit, in->target); return; }
    if (!strncmp(m,"BBS",3)) { fprintf(f, "if ((lynx_mem_read(0x%02X) & (1u<<%d)) != 0) goto L_%04X;", in->operand, in->bit, in->target); return; }

    /* conditional branches */
    {
        const char *cond = branch_cond(m);
        if (cond) {
            if (is_label(fn, in->target))
                fprintf(f, "if (%s) goto L_%04X;", cond, in->target);
            else if (is_func(t, in->target))
                fprintf(f, "if (%s) { lynx_func_%04X(); return; }", cond, in->target);
            else
                fprintf(f, "if (%s) { lynx_ext_jmp(0x%04X); return; }", cond, in->target);
            return;
        }
    }

    /* unconditional control transfer */
    if (!strcmp(m,"BRA") || !strcmp(m,"JMP")) {
        if (in->mode == AM_IND) { fprintf(f, "lynx_jmp_indirect(lynx_mem_read16(0x%04X)); return;", in->operand); return; }
        if (in->mode == AM_IAX) { fprintf(f, "lynx_jmp_indirect(lynx_mem_read16((uint16_t)(0x%04X + lynx_cpu.x))); return;", in->operand); return; }
        if (is_label(fn, in->target))      fprintf(f, "goto L_%04X;", in->target);
        else if (is_func(t, in->target))   fprintf(f, "lynx_func_%04X(); return;", in->target);
        else if (in_image(t, rom, sz, base, in->target)) fprintf(f, "goto L_%04X; /* intra */", in->target);
        else                               fprintf(f, "lynx_ext_jmp(0x%04X); return;", in->target);
        return;
    }
    if (!strcmp(m,"JSR")) {
        if (is_func(t, in->target))        fprintf(f, "lynx_func_%04X();", in->target);
        else                               fprintf(f, "lynx_boot_call(0x%04X);", in->target);
        return;
    }
    if (!strcmp(m,"RTS") || !strcmp(m,"RTI")) { fprintf(f, "return;"); return; }
    if (!strcmp(m,"BRK")) { fprintf(f, "lynx_unimpl(0x00); return; /* BRK */"); return; }
    if (!strcmp(m,"WAI") || !strcmp(m,"STP")) { fprintf(f, "return; /* %s */", m); return; }

    fprintf(f, "lynx_unimpl(0x%02X); /* %s unhandled */", in->opcode, m);
}

int emit_functions(const char *outdir, const uint8_t *rom, size_t rom_size,
                   uint16_t base, const func_table_t *t, const char *rom_label) {
    char path[1024];

    /* header: prototypes */
    snprintf(path, sizeof(path), "%s/recomp_funcs.h", outdir);
    FILE *h = fopen(path, "wb");
    if (!h) return -1;
    fprintf(h,
        "/* recomp_funcs.h - generated by m65c02recomp.\n"
        " * Source ROM: %s\n"
        " * %d functions discovered. Do not edit by hand. */\n"
        "#ifndef RECOMP_FUNCS_H\n#define RECOMP_FUNCS_H\n"
        "#include \"lynxrecomp/recomp_rt.h\"\n\n",
        rom_label ? rom_label : "(unknown)", t->nfuncs);
    for (int i = 0; i < t->nfuncs; i++)
        fprintf(h, "void lynx_func_%04X(void);\n", t->funcs[i].start);
    fprintf(h, "\n#endif\n");
    fclose(h);

    /* body */
    snprintf(path, sizeof(path), "%s/recomp_funcs.c", outdir);
    FILE *f = fopen(path, "wb");
    if (!f) return -1;
    fprintf(f,
        "/* recomp_funcs.c - generated by m65c02recomp.\n"
        " * Source ROM: %s\n"
        " * Recompiled 65SC02 -> C. Each line carries its address + disassembly.\n"
        " * Do not edit by hand. */\n"
        "#include \"recomp_funcs.h\"\n\n",
        rom_label ? rom_label : "(unknown)");

    for (int i = 0; i < t->nfuncs; i++) {
        const func_t *fn = &t->funcs[i];
        fprintf(f, "/* lynx_func_%04X: $%04X-$%04X (%d bytes)%s */\n",
                fn->start, fn->start, (uint16_t)(fn->end - 1),
                fn->end - fn->start, fn->reaches_ret ? "" : ", no RTS");
        fprintf(f, "void lynx_func_%04X(void) {\n", fn->start);

        uint16_t addr = fn->start;
        while (addr < fn->end) {
            size_t off = (size_t)(addr - base);
            uint8_t tmp[3] = {0,0,0};
            size_t avail = rom_size - off;
            tmp[0] = rom[off];
            if (avail > 1) tmp[1] = rom[off+1];
            if (avail > 2) tmp[2] = rom[off+2];

            insn_t in;
            m65c02_decode(tmp, addr, &in);
            if (in.len > avail) break;

            if (is_branch_target(fn, addr))
                fprintf(f, "L_%04X:\n", addr);

            char dis[48];
            m65c02_format(&in, dis, sizeof(dis));
            fprintf(f, "    /* %04X: %-18s */ ", addr, dis);
            emit_insn(f, &in, fn, t, rom, rom_size, base);
            fprintf(f, "\n");

            addr = (uint16_t)(addr + in.len);
        }
        /* fall-through safety: a function that ran off its end returns. */
        fprintf(f, "}\n\n");
    }
    fclose(f);
    return 0;
}
